name       : ktexteditor
version    : 5.47.0
release    : 21
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.47/ktexteditor-5.47.0.tar.xz : 6b4ae2ea3c00dd2d7dc4c53f7760c750f8fee8aece4bcbc938064cadd34c08cc
license    :
    - GPL-2.0
    - LGPL-2.0
    - LGPL-2.1
component  : desktop.library
optimize   : lto
summary    : Full text editor component
description: |
    Full text editor component.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(libgit2)
    - pkgconfig(Qt5Qml)
    - pkgconfig(Qt5Script)
    - pkgconfig(Qt5UiTools)
    - pkgconfig(Qt5XmlPatterns)
    - extra-cmake-modules
    - karchive-devel
    - kconfig-devel
    - kguiaddons-devel
    - ki18n-devel
    - kiconthemes-devel
    - kio-devel
    - kparts-devel
    - sonnet-devel
    - syntax-highlighting-devel
rundeps    :
    - devel :
        - kparts-devel
setup      : |
    %patch -p1 < $pkgfiles/security/cve-2018-10361.patch
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
