name       : ktexteditor
version    : 5.70.1
release    : 46
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.70/ktexteditor-5.70.1.tar.xz : c7b568e75c147161992f8875fe36fb46885bccddb63c22edaf81071583f4204c
homepage   : https://community.kde.org/Frameworks
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
component  : desktop.library
optimize   : lto
summary    : Full text editor component
description: |
    Full text editor component.
builddeps  :
    - pkgconfig(editorconfig)
    - pkgconfig(libgit2)
    - pkgconfig(Qt5Qml)
    - pkgconfig(Qt5Script)
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
    - karchive-devel
    - kguiaddons-devel
    - ki18n-devel
    - kio-devel
    - kparts-devel
    - kwindowsystem-devel
    - sonnet-devel
    - syntax-highlighting-devel
rundeps    :
    - devel :
        - kparts-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
