name       : ktexteditor
version    : 5.35.0
release    : 5
source     :
    - https://download.kde.org/stable/frameworks/5.35/ktexteditor-5.35.0.tar.xz : b61111a95a5e9f498372006ae5e421ae21536293ca9fc75fc7f8b2ed8accc88e
license    :
    - GPL-2.0
    - LGPL-2.0
    - LGPL-2.1
component  : desktop.library
summary    : Full text editor component
description: |
    Full text editor component.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(libgit2)
    - pkgconfig(Qt5Script)
    - pkgconfig(Qt5XmlPatterns)
    - extra-cmake-modules
    - karchive-devel
    - kconfig-devel
    - kguiaddons-devel
    - ki18n-devel
    - kiconthemes-devel
    - kio-devel
    - kparts-devel
    - sonnet-devel
    - syntax-highlighting-devel
rundeps    :
    - devel :
        - kparts-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
