name       : ktexteditor
version    : 5.36.0
release    : 6
source     :
    - https://download.kde.org/stable/frameworks/5.36/ktexteditor-5.36.0.tar.xz : f9a0109aff18175ef528186e099d0881b977dde7435c433c5541df44b5a18609
license    :
    - GPL-2.0
    - LGPL-2.0
    - LGPL-2.1
component  : desktop.library
summary    : Full text editor component
description: |
    Full text editor component.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(libgit2)
    - pkgconfig(Qt5Script)
    - pkgconfig(Qt5XmlPatterns)
    - extra-cmake-modules
    - karchive-devel
    - kconfig-devel
    - kguiaddons-devel
    - ki18n-devel
    - kiconthemes-devel
    - kio-devel
    - kparts-devel
    - sonnet-devel
    - syntax-highlighting-devel
rundeps    :
    - devel :
        - kparts-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
