name       : ktexteditor
version    : 5.76.0
release    : 51
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.76/ktexteditor-5.76.0.tar.xz : 6f937b7af06562a238f091deef9c4332e94311a697af8466b7f091720eaab2b2
homepage   : https://community.kde.org/Frameworks
license    :
    - BSD-2-Clause
    - LGPL-2.0-or-later
    - LGPL-2.1-only
    - LGPL-2.1-or-later
component  : desktop.library
optimize   : lto
summary    : Full text editor component
description: |
    Full text editor component.
builddeps  :
    - pkgconfig(editorconfig)
    - pkgconfig(libgit2)
    - pkgconfig(Qt5Qml)
    - pkgconfig(Qt5Script)
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
    - karchive-devel
    - kguiaddons-devel
    - ki18n-devel
    - kio-devel
    - kparts-devel
    - kwindowsystem-devel
    - sonnet-devel
    - syntax-highlighting-devel
rundeps    :
    - devel :
        - kparts-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
