name       : ktexteditor
version    : 5.28.0
release    : 2
source     :
    - http://download.kde.org/stable/frameworks/5.28/ktexteditor-5.28.0.tar.xz : d8a1f53a2bd14101d95e9d8db6faabda88450a9b571947e0bd0f2eadba2881ea
license    :
    - GPL-2.0
    - LGPL-2.0
    - LGPL-2.1
component  : desktop.library
summary    : Full text editor component
description: |
    Full text editor component.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(libgit2)
    - pkgconfig(Qt5Script)
    - pkgconfig(Qt5XmlPatterns)
    - extra-cmake-modules
    - karchive-devel
    - kconfig-devel
    - kguiaddons-devel
    - ki18n-devel
    - kiconthemes-devel
    - kio-devel
    - kparts-devel
    - sonnet-devel
rundeps    :
    - devel :
        - kparts-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
