name       : ktexteditor
version    : 5.65.0
release    : 40
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.65/ktexteditor-5.65.0.tar.xz : 830aed1f7d181bf79e57a11373046baf762507a30fe1adc19cb2fc13d9be60c0
homepage   : https://community.kde.org/Frameworks
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
component  : desktop.library
optimize   : lto
summary    : Full text editor component
description: |
    Full text editor component.
builddeps  :
    - pkgconfig(editorconfig)
    - pkgconfig(libgit2)
    - pkgconfig(Qt5Qml)
    - pkgconfig(Qt5Script)
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
    - karchive-devel
    - kguiaddons-devel
    - ki18n-devel
    - kio-devel
    - kparts-devel
    - sonnet-devel
    - syntax-highlighting-devel
rundeps    :
    - devel :
        - kparts-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
