name       : ktexteditor
version    : 5.89.0
release    : 64
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.89/ktexteditor-5.89.0.tar.xz : 67ad913c86a0845d097e3145e15d7218480e1af87133561da7b2295c1b416f09
homepage   : https://community.kde.org/Frameworks
license    :
    - BSD-2-Clause
    - LGPL-2.0-or-later
    - LGPL-2.1-only
    - LGPL-2.1-or-later
component  : desktop.library
summary    : Full text editor component
description: |
    Full text editor component.
optimize   : lto
builddeps  :
    - pkgconfig(Qt5Script)
    - pkgconfig(Qt5Quick)
    - pkgconfig(editorconfig)
    - karchive-devel
    - kguiaddons-devel
    - kparts-devel
    - syntax-highlighting-devel
rundeps    :
    - devel :
        - kparts-devel
        - syntax-highlighting-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
