name       : ktexteditor
version    : 5.25.0
release    : 1
source     :
    - http://download.kde.org/stable/frameworks/5.25/ktexteditor-5.25.0.tar.xz : 4a225b73c33dc0cc49fdf67eab60f119eca74b2e8a7801af16ecc5b87bf53e1b
license    :
    - GPL-2.0
    - LGPL-2.0
    - LGPL-2.1
component  : desktop.library
summary    : Full text editor component
description: |
    Full text editor component.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(libgit2)
    - pkgconfig(Qt5Script)
    - pkgconfig(Qt5XmlPatterns)
    - extra-cmake-modules
    - karchive-devel
    - kconfig-devel
    - kguiaddons-devel
    - ki18n-devel
    - kiconthemes-devel
    - kio-devel
    - kparts-devel
    - sonnet-devel
rundeps    :
    - devel :
        - kparts-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
