name       : ktexteditor
version    : 5.85.0
release    : 61
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.85/ktexteditor-5.85.0.tar.xz : d550711e98e1ebdfcb74840e55328ad4ab40e1a90038f6ae3f64d5c3d19fddc8
homepage   : https://community.kde.org/Frameworks
license    :
    - BSD-2-Clause
    - LGPL-2.0-or-later
    - LGPL-2.1-only
    - LGPL-2.1-or-later
component  : desktop.library
summary    : Full text editor component
description: |
    Full text editor component.
optimize   : lto
builddeps  :
    - pkgconfig(Qt5Script)
    - pkgconfig(Qt5Quick)
    - pkgconfig(editorconfig)
    - pkgconfig(libgit2)
    - karchive-devel
    - kguiaddons-devel
    - kparts-devel
    - syntax-highlighting-devel
rundeps    :
    - devel :
        - kparts-devel
        - syntax-highlighting-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
