name       : ktexteditor
version    : 5.46.0
release    : 19
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.46/ktexteditor-5.46.0.tar.xz : 0bd58aadcbbf61acea70a89bb91be798990db81f413e20ba177188e046b45efa
license    :
    - GPL-2.0
    - LGPL-2.0
    - LGPL-2.1
component  : desktop.library
optimize   : lto
summary    : Full text editor component
description: |
    Full text editor component.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(libgit2)
    - pkgconfig(Qt5Qml)
    - pkgconfig(Qt5Script)
    - pkgconfig(Qt5UiTools)
    - pkgconfig(Qt5XmlPatterns)
    - extra-cmake-modules
    - karchive-devel
    - kconfig-devel
    - kguiaddons-devel
    - ki18n-devel
    - kiconthemes-devel
    - kio-devel
    - kparts-devel
    - sonnet-devel
    - syntax-highlighting-devel
rundeps    :
    - devel :
        - kparts-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
