name       : ktexteditor
version    : 5.60.0
release    : 34
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.60/ktexteditor-5.60.0.tar.xz : 7484dfaa4df868c8193e15cc760b3ce7e8e0948daaa4a1b3ca6b96550041385d
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
component  : desktop.library
optimize   : lto
summary    : Full text editor component
description: |
    Full text editor component.
builddeps  :
    - pkgconfig(editorconfig)
    - pkgconfig(libgit2)
    - pkgconfig(Qt5Qml)
    - pkgconfig(Qt5Script)
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
    - karchive-devel
    - kguiaddons-devel
    - ki18n-devel
    - kiconthemes-devel
    - kio-devel
    - kparts-devel
    - sonnet-devel
    - syntax-highlighting-devel
rundeps    :
    - devel :
        - kparts-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
